import type { Metadata } from "next";
import { Geist_Mono, Kumbh_Sans, Nunito } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const kumbhSans = Kumbh_Sans({
  variable: "--font-kumbh-sans",
  subsets: ["latin"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.variable} ${kumbhSans.variable} ${nunito.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
